name 'apache'
maintainer 'Ritwij Shastri'
maintainer_email 'ritiwj@live.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
